In [1]:
%run ../__init__.py

## Data preprocessing with Tfidf

In [2]:
budget_train = pd.read_csv('../data/train_cleaned.csv', index_col=0)
budget_test = pd.read_csv('../data/test_clean.csv', index_col=0)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [8]:
budget_train.isnull().sum()

Function                  0
Use                       0
Sharing                   0
Reporting                 0
Student_Type              0
Position_Type             0
Object_Type               0
Pre_K                     0
Operating_Status          0
Object_Description        0
Text_2                    0
SubFund_Description       0
Job_Title_Description     0
Text_3                    0
Text_4                    0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Facility_or_Department    0
Position_Extra            0
Total                     0
Program_Description       0
Fund_Description          0
Text_1                    0
combined_text             0
dtype: int64

In [9]:
budget_test.isnull().sum()

ID                        0
Object_Description        0
Program_Description       0
SubFund_Description       0
Job_Title_Description     0
Facility_or_Department    0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Position_Extra            0
Text_4                    0
Total                     0
Text_2                    0
Text_3                    0
Fund_Description          0
Text_1                    0
dtype: int64

In [5]:
for col in budget_test[word_predictors]:
    budget_test[col] = budget_test[word_predictors].loc[:,[col]].fillna(' ')

In [6]:
for col in budget_train[word_predictors]:
    budget_train[col] = budget_train[word_predictors].loc[:,[col]].fillna(' ')

In [10]:
label = LabelEncoder()

In [11]:
class ItemSelector(BaseEstimator, TransformerMixin):
    """For data grouped by feature, select subset of data at a provided key.

    The data is expected to be stored in a 2D data structure, where the first
    index is over features and the second is over samples.  i.e.

    >> len(data[key]) == n_samples

    Please note that this is the opposite convention to scikit-learn feature
    matrixes (where the first index corresponds to sample).

    ItemSelector only requires that the collection implement getitem
    (data[key]).  Examples include: a dict of lists, 2D numpy array, Pandas
    DataFrame, numpy record array, etc.

    >> data = {'a': [1, 5, 2, 5, 2, 8],
               'b': [9, 4, 1, 4, 1, 3]}
    >> ds = ItemSelector(key='a')
    >> data['a'] == ds.transform(data)

    Parameters
     ----------
    key : hashable, required
        The key corresponding to the desired value in a mappable.
    """
    def __init__(self, key):
        self.key = key

    def fit(self, x, y=None):
        return self

    def transform(self, data_dict):
        return data_dict[self.key]
    

In [12]:
class ArrayCaster(BaseEstimator, TransformerMixin):
    def fit(self, x, y=None):
        return self

    def transform(self, data):
        return np.transpose(np.matrix(data))

In [11]:
targets

['Function',
 'Use',
 'Sharing',
 'Reporting',
 'Student_Type',
 'Position_Type',
 'Object_Type',
 'Pre_K',
 'Operating_Status']

In [13]:
# 400,000+ examples, 14 features
X = budget_train[predictors] 
y = label.fit_transform(budget_train['Sharing'])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = .2, random_state=42)
                                                

In [14]:
# feature union transformer list 
transformer_list = [
    ('Object_Description', Pipeline([
                ('selector', ItemSelector(key='Object_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_2', Pipeline([
                ('selector', ItemSelector(key='Text_2')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('SubFund_Description', Pipeline([
                ('selector', ItemSelector(key='SubFund_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Job_Title_Description', Pipeline([
                ('selector', ItemSelector(key='Job_Title_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_3', Pipeline([
                ('selector', ItemSelector(key='Text_3')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_4', Pipeline([
                ('selector', ItemSelector(key='Text_4')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Sub_Object_Description', Pipeline([
                ('selector', ItemSelector(key='Sub_Object_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Location_Description', Pipeline([
                ('selector', ItemSelector(key='Location_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Function_Description', Pipeline([
                ('selector', ItemSelector(key='Function_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Facility_or_Department', Pipeline([
                ('selector', ItemSelector(key='Facility_or_Department')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Position_Extra', Pipeline([
                ('selector', ItemSelector(key='Position_Extra')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Program_Description', Pipeline([
                ('selector', ItemSelector(key='Program_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Fund_Description', Pipeline([
                ('selector', ItemSelector(key='Fund_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_1', Pipeline([
                ('selector', ItemSelector(key='Text_1')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
#     ('FTE', Pipeline([
#                 ('selector', ItemSelector(key='FTE')),
#                 ('scaler', StandardScaler()),
#                 ('caster', ArrayCaster()),
#             ])),
#     ('Total', Pipeline([
#                 ('selector', ItemSelector(key='Total')),
#                 ('scaler', StandardScaler()),
#                 ('caster', ArrayCaster()),
#             ])),
]

### Don't include numerical columns in final feature union since it decreased scores and increased log loss- in general, in the original data, numerical features had a lot of missing values and some incorrect values for data that were there

In [15]:
# create pipeline
model_pipeline = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", LogisticRegression(C=10)),
])

In [16]:
X_test = budget_test

In [17]:
sharing_model = model_pipeline.fit(X_train, y_train)

In [18]:
sharing_model.score(X_train, y_train)

0.9760009493443591

In [19]:
val_proba = sharing_model.predict_proba(X_val)

In [20]:
predict_proba = sharing_model.predict_proba(X_test)

In [21]:
label.classes_

array(['Sharing__Leadership & Management', 'Sharing__NO_LABEL',
       'Sharing__School Reported', 'Sharing__School on Central Budgets',
       'Sharing__Shared Services'], dtype=object)

In [22]:
val_proba

array([[  4.78558354e-10,   2.79223169e-07,   9.99999591e-01,
          3.90449887e-08,   8.99418957e-08],
       [  6.82890595e-06,   9.93921224e-03,   9.80800772e-01,
          8.95850187e-03,   2.94685027e-04],
       [  3.24960819e-05,   4.37203155e-02,   9.53500251e-01,
          1.43585159e-04,   2.60335220e-03],
       ..., 
       [  3.86003168e-10,   1.77628423e-05,   9.99971011e-01,
          1.82101563e-09,   1.12241755e-05],
       [  8.49818216e-06,   9.90924096e-01,   8.94351933e-03,
          7.73690795e-08,   1.23809223e-04],
       [  2.06942214e-05,   3.72064005e-08,   9.99200114e-01,
          7.79154285e-04,   3.48925388e-10]])

In [23]:
log_loss(y_val, val_proba)

0.086858334261948555

In [24]:
from sklearn.externals import joblib

In [33]:
joblib.dump(sharing_model, 'sharing_model.pkl')

['sharing_model.pkl']

In [25]:
def score_eval(model, X_val, y_val):
    preds = model.predict(X_val)
    proba = model.predict_proba(X_val)
    return {
        'log_loss': log_loss(y_val, proba),
        'accuracy': accuracy_score(y_val, preds),
        'confmat': confusion_matrix(y_val, preds),
        'clf_rep': classification_report(y_val, preds)
    }

In [26]:
results = score_eval(sharing_model, X_val, y_val)

print('-'*60)
for key, value in results.items():
    print(key)
    print(value)
    print('-'*60)

------------------------------------------------------------
log_loss
0.0868583342619
------------------------------------------------------------
accuracy
0.974243029879
------------------------------------------------------------
confmat
[[ 3147    70    51    48   182]
 [   76 11125   575    35   162]
 [    5   191 50595     1     5]
 [   43    38    56  5130   101]
 [  145   117    49   112  7997]]
------------------------------------------------------------
clf_rep
             precision    recall  f1-score   support

          0       0.92      0.90      0.91      3498
          1       0.96      0.93      0.95     11973
          2       0.99      1.00      0.99     50797
          3       0.96      0.96      0.96      5368
          4       0.95      0.95      0.95      8420

avg / total       0.97      0.97      0.97     80056

------------------------------------------------------------


In [28]:
classes = label.classes_

In [29]:
sharing_probability = pd.DataFrame(predict_proba, columns=classes)

In [31]:
sharing_probability.shape

(50064, 5)

In [32]:
sharing_probability.to_csv('sharing_probability.csv')