In [1]:
%run ../__init__.py

## Data preprocessing with Tfidf

In [2]:
budget_train = pd.read_csv('../data/train_cleaned.csv', index_col=0)
budget_test = pd.read_csv('../data/test_clean.csv', index_col=0)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
budget_train.isnull().sum()

Function                  0
Use                       0
Sharing                   0
Reporting                 0
Student_Type              0
Position_Type             0
Object_Type               0
Pre_K                     0
Operating_Status          0
Object_Description        0
Text_2                    0
SubFund_Description       0
Job_Title_Description     0
Text_3                    0
Text_4                    0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Facility_or_Department    0
Position_Extra            0
Total                     0
Program_Description       0
Fund_Description          0
Text_1                    0
combined_text             0
dtype: int64

In [6]:
budget_test.isnull().sum()

ID                        0
Object_Description        0
Program_Description       0
SubFund_Description       0
Job_Title_Description     0
Facility_or_Department    0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Position_Extra            0
Text_4                    0
Total                     0
Text_2                    0
Text_3                    0
Fund_Description          0
Text_1                    0
dtype: int64

In [3]:
for col in budget_test[word_predictors]:
    budget_test[col] = budget_test[word_predictors].loc[:,[col]].fillna(' ')

In [4]:
for col in budget_train[word_predictors]:
    budget_train[col] = budget_train[word_predictors].loc[:,[col]].fillna(' ')

In [7]:
label = LabelEncoder()

In [8]:
class ItemSelector(BaseEstimator, TransformerMixin):
    """For data grouped by feature, select subset of data at a provided key.

    The data is expected to be stored in a 2D data structure, where the first
    index is over features and the second is over samples.  i.e.

    >> len(data[key]) == n_samples

    Please note that this is the opposite convention to scikit-learn feature
    matrixes (where the first index corresponds to sample).

    ItemSelector only requires that the collection implement getitem
    (data[key]).  Examples include: a dict of lists, 2D numpy array, Pandas
    DataFrame, numpy record array, etc.

    >> data = {'a': [1, 5, 2, 5, 2, 8],
               'b': [9, 4, 1, 4, 1, 3]}
    >> ds = ItemSelector(key='a')
    >> data['a'] == ds.transform(data)

    Parameters
     ----------
    key : hashable, required
        The key corresponding to the desired value in a mappable.
    """
    def __init__(self, key):
        self.key = key

    def fit(self, x, y=None):
        return self

    def transform(self, data_dict):
        return data_dict[self.key]
    

In [9]:
class ArrayCaster(BaseEstimator, TransformerMixin):
    def fit(self, x, y=None):
        return self

    def transform(self, data):
        return np.transpose(np.matrix(data))

In [10]:
targets

['Function',
 'Use',
 'Sharing',
 'Reporting',
 'Student_Type',
 'Position_Type',
 'Object_Type',
 'Pre_K',
 'Operating_Status']

In [11]:
# 400,000+ examples, 14 features
X = budget_train[predictors] 
y = label.fit_transform(budget_train['Operating_Status'])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = .2, random_state=42)
                                                

In [12]:
# feature union transformer list 
transformer_list = [
    ('Object_Description', Pipeline([
                ('selector', ItemSelector(key='Object_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Text_2', Pipeline([
                ('selector', ItemSelector(key='Text_2')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('SubFund_Description', Pipeline([
                ('selector', ItemSelector(key='SubFund_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Job_Title_Description', Pipeline([
                ('selector', ItemSelector(key='Job_Title_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Text_3', Pipeline([
                ('selector', ItemSelector(key='Text_3')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Text_4', Pipeline([
                ('selector', ItemSelector(key='Text_4')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Sub_Object_Description', Pipeline([
                ('selector', ItemSelector(key='Sub_Object_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Location_Description', Pipeline([
                ('selector', ItemSelector(key='Location_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Function_Description', Pipeline([
                ('selector', ItemSelector(key='Function_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Facility_or_Department', Pipeline([
                ('selector', ItemSelector(key='Facility_or_Department')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Position_Extra', Pipeline([
                ('selector', ItemSelector(key='Position_Extra')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Program_Description', Pipeline([
                ('selector', ItemSelector(key='Program_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Fund_Description', Pipeline([
                ('selector', ItemSelector(key='Fund_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
    ('Text_1', Pipeline([
                ('selector', ItemSelector(key='Text_1')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=10)),
            ])),
#     ('FTE', Pipeline([
#                 ('selector', ItemSelector(key='FTE')),
#                 ('scaler', StandardScaler()),
#                 ('caster', ArrayCaster()),
#             ])),
#     ('Total', Pipeline([
#                 ('selector', ItemSelector(key='Total')),
#                 ('scaler', StandardScaler()),
#                 ('caster', ArrayCaster()),
#             ])),
]

### Don't include numerical columns in final feature union since it decreased scores and increased log loss- in general, in the original data, numerical features had a lot of missing values and some incorrect values for data that were there

## Experiment with adaboost

In [13]:
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [15]:
ada_pipeline = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", AdaBoostClassifier(DecisionTreeClassifier(max_depth=5),
                              n_estimators=200, 
                              learning_rate=.5)),
])

In [16]:
ada_model = ada_pipeline.fit(X_train, y_train)

In [17]:
ada_model.score(X_train, y_train)

0.96681979008247432

In [18]:
val_proba = ada_model.predict_proba(X_val)

In [19]:
# ada log_loss
log_loss(y_val, val_proba)

0.72425482510972894

## Experimenting with randomforest

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
forest_pipeline = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", RandomForestClassifier(n_estimators=100, max_depth=5)),
])

In [22]:
forest_model = forest_pipeline.fit(X_train, y_train)

In [23]:
forest_model.score(X_train, y_train)

0.90904718928490014

In [24]:
val_proba = forest_model.predict_proba(X_val)

In [25]:
log_loss(y_val, val_proba)

0.27822697178971878

## Experimenting with xgb 

In [13]:
# create pipeline
model_pipeline = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", xgb.XGBClassifier()),
])

In [11]:
import xgboost as xgb

/opt/conda/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [14]:
xgbc_model = model_pipeline.fit(X_train, y_train)

In [16]:
xgbc_model.score(X_train, y_train)

0.97277505222955396

In [17]:
val_proba = xgbc_model.predict_proba(X_val)

In [18]:
# xgbc log_loss 
log_loss(y_val, val_proba)

0.099883956633913584

## Experiment with stacking

In [27]:
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error
from IPython.display import display
import numpy as np

from sklearn.model_selection import ShuffleSplit

In [42]:
rf_pipe_1 = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", RandomForestClassifier(n_estimators=100)),
])

gb_pipe_1 = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", RandomForestClassifier(n_estimators=100)),
])

lr_pipe_1 = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", RandomForestClassifier(n_estimators=100)),
])

In [43]:
X_sub_1, X_sub_2, y_sub_1, y_sub_2 = train_test_split(X_train, y_train, test_size = .5, random_state = 42)

In [44]:
for model in (rf_pipe_1, gb_pipe_1, lr_pipe_1):
    model.fit(X_sub_1, y_sub_1)

In [45]:
for model in (rf_pipe_1, gb_pipe_1, lr_pipe_1):
    print(model.score(X_val, y_val))

0.985585090437
0.985460177875
0.985585090437


In [46]:
layer_1_preds = []
for model in (rf_pipe_1, gb_pipe_1, lr_pipe_1):
    layer_1_preds.append(model.predict(X_sub_2).reshape(-1,1))

In [47]:
blended = np.concatenate(layer_1_preds, axis=1)

In [48]:
blended.shape

(160111, 3)

In [50]:
blender = RandomForestClassifier(n_estimators=100)

In [51]:
blender.fit(blended, y_sub_2)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [53]:
layer_1_val_preds = []
for model in [rf_pipe_1, gb_pipe_1, lr_pipe_1]:
    layer_1_val_preds.append(model.predict(X_val).reshape(-1,1))

In [58]:
blended_val = np.concatenate(layer_1_val_preds, axis=1)

In [57]:
blended.shape

(160111, 3)

In [59]:
val_preds = blender.predict(blended_val)

In [60]:
val_proba = blender.predict_proba(blended_val)

In [62]:
r2_score(y_val, val_preds)

0.90371957182024765

In [61]:
log_loss(y_val, blended_val)

1.1188189853011468

## Experiment with different C for logistic regression

In [41]:
op_stat_model.score(X_train, y_train)

0.98660924798810823

In [42]:
val_proba = op_stat_model.predict_proba(X_val)

In [19]:
# C=10
log_loss(y_val, val_proba)

0.044086925832810243

In [20]:
#normal C
log_loss(y_val, val_proba)

0.047490405186274731

In [21]:
from sklearn.externals import joblib

In [23]:
def score_eval(model, X_val, y_val):
    preds = model.predict(X_val)
    proba = model.predict_proba(X_val)
    return {
        'log_loss': log_loss(y_val, proba),
        'accuracy': accuracy_score(y_val, preds),
        'confmat': confusion_matrix(y_val, preds),
        'clf_rep': classification_report(y_val, preds)
    }

In [24]:
results = score_eval(op_stat_model, X_val, y_val)

print('-'*60)
for key, value in results.items():
    print(key)
    print(value)
    print('-'*60)

------------------------------------------------------------
log_loss
0.0474904051863
------------------------------------------------------------
accuracy
0.984460877386
------------------------------------------------------------
confmat
[[ 9158    25   495]
 [   35  1321   373]
 [  307     9 68333]]
------------------------------------------------------------
clf_rep
             precision    recall  f1-score   support

          0       0.96      0.95      0.96      9678
          1       0.97      0.76      0.86      1729
          2       0.99      1.00      0.99     68649

avg / total       0.98      0.98      0.98     80056

------------------------------------------------------------
