In [1]:
%run ../__init__.py

## Data preprocessing with Tfidf

In [2]:
budget_train = pd.read_csv('../data/train_cleaned.csv', index_col=0)
budget_test = pd.read_csv('../data/test_clean.csv', index_col=0)

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [7]:
budget_train.isnull().sum()

Function                  0
Use                       0
Sharing                   0
Reporting                 0
Student_Type              0
Position_Type             0
Object_Type               0
Pre_K                     0
Operating_Status          0
Object_Description        0
Text_2                    0
SubFund_Description       0
Job_Title_Description     0
Text_3                    0
Text_4                    0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Facility_or_Department    0
Position_Extra            0
Total                     0
Program_Description       0
Fund_Description          0
Text_1                    0
combined_text             0
dtype: int64

In [8]:
budget_test.isnull().sum()

ID                        0
Object_Description        0
Program_Description       0
SubFund_Description       0
Job_Title_Description     0
Facility_or_Department    0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Position_Extra            0
Text_4                    0
Total                     0
Text_2                    0
Text_3                    0
Fund_Description          0
Text_1                    0
dtype: int64

In [5]:
for col in budget_test[word_predictors]:
    budget_test[col] = budget_test[word_predictors].loc[:,[col]].fillna(' ')

In [6]:
for col in budget_train[word_predictors]:
    budget_train[col] = budget_train[word_predictors].loc[:,[col]].fillna(' ')

In [9]:
label = LabelEncoder()

In [10]:
class ItemSelector(BaseEstimator, TransformerMixin):
    """For data grouped by feature, select subset of data at a provided key.

    The data is expected to be stored in a 2D data structure, where the first
    index is over features and the second is over samples.  i.e.

    >> len(data[key]) == n_samples

    Please note that this is the opposite convention to scikit-learn feature
    matrixes (where the first index corresponds to sample).

    ItemSelector only requires that the collection implement getitem
    (data[key]).  Examples include: a dict of lists, 2D numpy array, Pandas
    DataFrame, numpy record array, etc.

    >> data = {'a': [1, 5, 2, 5, 2, 8],
               'b': [9, 4, 1, 4, 1, 3]}
    >> ds = ItemSelector(key='a')
    >> data['a'] == ds.transform(data)

    Parameters
     ----------
    key : hashable, required
        The key corresponding to the desired value in a mappable.
    """
    def __init__(self, key):
        self.key = key

    def fit(self, x, y=None):
        return self

    def transform(self, data_dict):
        return data_dict[self.key]
    

In [11]:
class ArrayCaster(BaseEstimator, TransformerMixin):
    def fit(self, x, y=None):
        return self

    def transform(self, data):
        return np.transpose(np.matrix(data))

In [12]:
targets

['Function',
 'Use',
 'Sharing',
 'Reporting',
 'Student_Type',
 'Position_Type',
 'Object_Type',
 'Pre_K',
 'Operating_Status']

In [13]:
# 400,000+ examples, 14 features
X = budget_train[predictors] 
y = label.fit_transform(budget_train['Object_Type'])

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = .2, random_state=42)
                                                

In [14]:
# feature union transformer list 
transformer_list = [
    ('Object_Description', Pipeline([
                ('selector', ItemSelector(key='Object_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_2', Pipeline([
                ('selector', ItemSelector(key='Text_2')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('SubFund_Description', Pipeline([
                ('selector', ItemSelector(key='SubFund_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Job_Title_Description', Pipeline([
                ('selector', ItemSelector(key='Job_Title_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_3', Pipeline([
                ('selector', ItemSelector(key='Text_3')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_4', Pipeline([
                ('selector', ItemSelector(key='Text_4')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Sub_Object_Description', Pipeline([
                ('selector', ItemSelector(key='Sub_Object_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Location_Description', Pipeline([
                ('selector', ItemSelector(key='Location_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Function_Description', Pipeline([
                ('selector', ItemSelector(key='Function_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Facility_or_Department', Pipeline([
                ('selector', ItemSelector(key='Facility_or_Department')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Position_Extra', Pipeline([
                ('selector', ItemSelector(key='Position_Extra')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Program_Description', Pipeline([
                ('selector', ItemSelector(key='Program_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Fund_Description', Pipeline([
                ('selector', ItemSelector(key='Fund_Description')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
    ('Text_1', Pipeline([
                ('selector', ItemSelector(key='Text_1')),
                ('tfidf', TfidfVectorizer(ngram_range=(1,2), token_pattern='(?u)\\b\\w\\w+\\b',min_df=100)),
            ])),
#     ('FTE', Pipeline([
#                 ('selector', ItemSelector(key='FTE')),
#                 ('scaler', StandardScaler()),
#                 ('caster', ArrayCaster()),
#             ])),
#     ('Total', Pipeline([
#                 ('selector', ItemSelector(key='Total')),
#                 ('scaler', StandardScaler()),
#                 ('caster', ArrayCaster()),
#             ])),
]

### Don't include numerical columns in final feature union since it decreased scores and increased log loss- in general, in the original data, numerical features had a lot of missing values and some incorrect values for data that were there

In [15]:
# create pipeline
model_pipeline = Pipeline([
    ("union", FeatureUnion(transformer_list=transformer_list)),
    ("clf", LogisticRegression()),
])

In [16]:
X_test = budget_test

In [17]:
object_model = model_pipeline.fit(X_train, y_train)

In [18]:
object_model.score(X_train, y_train)

0.98563492088276539

In [19]:
val_proba = object_model.predict_proba(X_val)

In [20]:
predict_proba = object_model.predict_proba(X_test)

In [21]:
label.classes_

array(['Object_Type__Base Salary/Compensation', 'Object_Type__Benefits',
       'Object_Type__Contracted Services',
       'Object_Type__Equipment & Equipment Lease', 'Object_Type__NO_LABEL',
       'Object_Type__Other Compensation/Stipend',
       'Object_Type__Other Non-Compensation',
       'Object_Type__Rent/Utilities',
       'Object_Type__Substitute Compensation',
       'Object_Type__Supplies/Materials',
       'Object_Type__Travel & Conferences'], dtype=object)

In [22]:
log_loss(y_val, val_proba)

0.055529605784008576

In [23]:
from sklearn.externals import joblib

In [24]:
joblib.dump(object_model, 'object_model.pkl')

['object_model.pkl']

In [25]:
def score_eval(model, X_val, y_val):
    preds = model.predict(X_val)
    proba = model.predict_proba(X_val)
    return {
        'log_loss': log_loss(y_val, proba),
        'accuracy': accuracy_score(y_val, preds),
        'confmat': confusion_matrix(y_val, preds),
        'clf_rep': classification_report(y_val, preds)
    }

In [26]:
results = score_eval(object_model, X_val, y_val)

print('-'*60)
for key, value in results.items():
    print(key)
    print(value)
    print('-'*60)

------------------------------------------------------------
log_loss
0.055529605784
------------------------------------------------------------
accuracy
0.983948735885
------------------------------------------------------------
confmat
[[19407     0     0     0    21     1     0     0     4     0     0]
 [    1 16958     0     0    22     1     0     0     0     0     0]
 [    1     0  1401     1    95     1     3     2     0     2     0]
 [    0     0     0   864    32     0     0     1     0     2     0]
 [   60    77    96    55 13187    63    68    24    11   321    38]
 [    2     0     0     0    50 12238     0     0     0     4     0]
 [    0     0    11     0    37     0  1246     1     0     7     0]
 [    0     0     7     0    11     0     8   602     0     5     0]
 [    0     0     0     0     1     1     0     0  5517     0     0]
 [    0     0     1     8   100     0     5     5     0  6347     0]
 [    0     0     0     0    14     1     0     0     0     3  1004]]
-

In [31]:
classes

array(['Object_Type__Base Salary/Compensation', 'Object_Type__Benefits',
       'Object_Type__Contracted Services',
       'Object_Type__Equipment & Equipment Lease', 'Object_Type__NO_LABEL',
       'Object_Type__Other Compensation/Stipend',
       'Object_Type__Other Non-Compensation',
       'Object_Type__Rent/Utilities',
       'Object_Type__Substitute Compensation',
       'Object_Type__Supplies/Materials',
       'Object_Type__Travel & Conferences'], dtype=object)

In [27]:
classes = label.classes_

In [28]:
object_probability = pd.DataFrame(predict_proba, columns=classes)

In [33]:
object_probability.head()

Object_Type__Base Salary/Compensation  Object_Type__Benefits  \
0                               0.000997               0.000874   
1                               0.000002               0.000027   
2                               0.124150               0.000228   
3                               0.124309               0.000229   
4                               0.961959               0.000069   

   Object_Type__Contracted Services  Object_Type__Equipment & Equipment Lease  \
0                          0.011927                                  0.001788   
1                          0.000133                                  0.000683   
2                          0.031427                                  0.003107   
3                          0.031453                                  0.003110   
4                          0.000132                                  0.000528   

   Object_Type__NO_LABEL  Object_Type__Other Compensation/Stipend  \
0               0.159595                                 0.027501   
1               0.076471                                 0.919148   
2               0.259603                                 0.002445   
3               0.258832                                 0.002453   
4               0.033431                                 0.000037   

   Object_Type__Other Non-Compensation  Object_Type__Rent/Utilities  \
0                             0.671651                     0.034227   
1                             0.001485                     0.000987   
2                             0.534627                     0.015696   
3                             0.535159                     0.015712   
4                             0.001649                     0.000429   

   Object_Type__Substitute Compensation  Object_Type__Supplies/Materials  \
0                              0.000163                         0.091201   
1                              0.000013                         0.000846   
2                              0.001858                         0.026382   
3                              0.001857                         0.026409   
4                              0.000003                         0.001311   

   Object_Type__Travel & Conferences  
0                           0.000076  
1                           0.000206  
2                           0.000476  
3                           0.000477  
4                           0.000451

In [34]:
object_probability.to_csv('object_probability.csv')